spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to AbidiBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@abidibank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384